TEMPLATE = app
QT = gui core network
CONFIG += qt warn_on console debug
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/dialog.ui
HEADERS = src/dialogimpl.h src/qrapidsharedownload.h src/debugutils.h
SOURCES = src/dialogimpl.cpp src/main.cpp src/qrapidsharedownload.cpp src/debugutils.cpp
